// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkJUDrl0lGR5f7q7QCa2FeeQPc-EgxWe8',
    appId: '1:833186742577:android:c1be8276f1a12dfa5eb010',
    messagingSenderId: '833186742577',
    projectId: 'msam-bf771',
    databaseURL: 'https://msam-bf771-default-rtdb.firebaseio.com',
    storageBucket: 'msam-bf771.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_FxFEy0lFQDFVCvgi0tqPL7eafmGes6g',
    appId: '1:833186742577:ios:a0f4d14a1b17b74b5eb010',
    messagingSenderId: '833186742577',
    projectId: 'msam-bf771',
    databaseURL: 'https://msam-bf771-default-rtdb.firebaseio.com',
    storageBucket: 'msam-bf771.appspot.com',
    androidClientId: '833186742577-3is26k2l0lhvhvq2r15ar46eda7ta0lk.apps.googleusercontent.com',
    iosBundleId: 'com.minshawi.part.two',
  );

}